name: Update README with Latest Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    name: Update README with latest repositories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with latest repositories
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updated README with latest repositories'
          MAX_LINES: 5
